services:
    nginx:
        image: nginx:1.27.2
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php
    php:
        build: ./docker/php
        ports:
            - "5173:5173"
        volumes:
            - ./src:/var/www/
    mysql:
        image: mysql:9.0.1
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"

    mailhog:
        image: mailhog/mailhog:latest
        ports:
        - "8025:8025"
        - "1025:1025"